### ISSUE TITLE
在MainActivity中的方法doublePressBackToQuit()可以吗？

### ISSUE THREAD

**Issue by vampireLyc** [DanteAndroid/Knowledge#11]
新手提问：在方法中
private void doublePressBackToQuit() {
        if (backPressed) {
            super.onBackPressed();//最终调用的是activity.finish()
            return;
        }
        backPressed = true;
        UI.showSnack(drawerLayout, R.string.leave_app);
        //点击两次返回键要在一定的时间范围内
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                backPressed = false;
            }
        }, 2000);
    }

如果用户在2000ms内点击了两次返回键，则这里Hander发出的message由主线程的Looper管理，既然这里Activity退出了，那么Looper是不是也退出了？

**Comment by DanteAndroid** [comment]
当然啦，activity退出了handler也回收了。
