### ISSUE TITLE
com.dante.knowledge.net.Json类中的gson创建时自定义序列化和排除特定字段方法

### ISSUE THREAD

**Issue by vampireLyc** [DanteAndroid/Knowledge#14]
com.dante.knowledge.net.Json类中的gson创建时设置了registerTypeAdapter和setExclusionStrategies方法，这两个方法在程序中的作用不是很明白。大神有时间的话，请指导。

**Comment by DanteAndroid** [comment]
- registerTypeAdapter: 一些Bean对象中，你会看到RealmList<RealmString>（如FreshCustomFields类），这是因为RealmObject不能使用List<String>作为成员变量，只能用RealmList, 而String需要封装成RealmString。至于registerTypeAdapter，就是用来解决这个问题的，具体怎么用我也不清楚，当时是网上直接copy的代码。
- setExclusionStrategies: 排除RealmObject，不让Gson解析（否则会报错）
你可以[参考这里](http://stackoverflow.com/questions/30097810/listobject-or-realmlistrealmobject-on-realm-android)
