### ISSUE TITLE
调用onfresh()方法的一点疑问

### ISSUE THREAD

**Issue by evilchaos** [DanteAndroid/Knowledge#15]
最近在学习您的代码 ，我有一个不懂的地方，就是您的onfresh()是在onActivityCreated周期内调用的，用于此网络取数据，然后再将其写到数据库里。ZhihuListAdapter构造方法是在onCreateView内执行的，它先于on fresh()方法执行，您在这个构造方法内进行了读数据库操作 zhihuStories=DB.findAll(ZhihuStory.class);tops = DB.findAll(ZhihuTop.class);那么应用第一次启动的时候，会先读数据库，但是此时结果应该是为空啊，因为此时onfresh还没有得到执行，但是我没有看到您在哪个地方再次调用onfresh方法，为什么程序会照样执行呢？

**Comment by DanteAndroid** [comment]
这玩意是Realm的好处之一，就是你数据库有内容的时候，相关的查询会实时得到更新。

请参考[这里的Auto-Updating Results部分](https://realm.io/cn/docs/java/latest/#section-14)
