### ISSUE TITLE
ZhihuDetailActivity 为什么要放在单独的进程里面？

### ISSUE THREAD

**Issue by mrldroid** [DanteAndroid/Knowledge#16]
求指教，一般来说能不用多进程就不用，不知道作者是如何考虑的？

**Comment by DanteAndroid** [comment]
因为webview会内存泄露

**Comment by mrldroid** [comment]
谢谢回复。但是把Activity 放在单独进程就能解决内存泄漏吗？有没有相关文章推荐一下？

**Comment by DanteAndroid** [comment]
http://my.oschina.net/zhibuji/blog/100580
