### ISSUE TITLE
知乎日报的下拉刷新问题

### ISSUE THREAD

**Issue by DomceyKoo** [DanteAndroid/Knowledge#17]
最近在学习大神您的代码。遇到一个问题：就是在MainActivity下的知乎日报fragment，下拉刷新，recyclerView无法更新。但是头条的banner却可以更新，而且新鲜事也可以实现下拉刷新。百思不得其解，跪求大神解惑。

**Comment by DanteAndroid** [comment]
realm存储数据的顺序问题，你可以试着找办法。请参考ZhihuModel类、ZhihuAdapter类
