### ISSUE TITLE
关于解析Gson后保存数据的问题

### ISSUE THREAD

**Issue by baifaqingsi** [DanteAndroid/Knowledge#3]
你好，我针对latest 这个API使用xUtils请求数据并用Gson+GsonFormat解析了数据，在解析的方法内能够正常解析出想要数据，解析完成之后放到了bean对象中并用两个List集合List<A>+List<B>分别存储了， 这两个list集合该怎样去返回呢？

**Comment by DanteAndroid** [comment]
什么怎么返回？你解析完成之后通知fragment或者activity，然后把adapter更新一下不就行了。参考ZhihuFragment中mvp的架构
