### ISSUE TITLE
能否指点一下妹知如何正常运行起来

### ISSUE THREAD

**Issue by ceowufan** [DanteAndroid/Knowledge#5]
你好,我下载了妹知之后导入studio出错,是不是还需要下载第三方库文件才能运行起来?第一次用不太懂,能否指点一下,谢谢

**Comment by DanteAndroid** [comment]
你可以把错误Log发过来。

**Comment by ceowufan** [comment]
Migrate Project to Gradle?
         This project does not use the Gradle build system. We recommend that you migrate to using the Gradle build system.

**Comment by DanteAndroid** [comment]
这个是由于你拉到的项目包含了我创建的screenshots也就是截图文件夹造成的。你只需要到文件管理器删除或者移动到其他地方，然后重新导入。

**Comment by ceowufan** [comment]
谢谢,貌似可以运行了.我新手,我想问问你的后台数据保存在哪里?是保存在服务器还是直接从知乎煎蛋取过来?

**Comment by DanteAndroid** [comment]
请查看ZhihuModel.class和FreshModel.class

**Comment by ceowufan** [comment]
我马上赞助你喝咖啡,以后我有什么不懂就问你了,可以加个QQ或者微信吗

**Comment by DanteAndroid** [comment]
当然。qq: 502273376。工作时间都在。
