### ISSUE TITLE
退出应用闪退

### ISSUE THREAD

**Issue by AndrWang** [DanteAndroid/Knowledge#7]
![image](https://cloud.githubusercontent.com/assets/10292984/14844551/b365ab6c-0c8a-11e6-8b66-94076dac766b.png)

**Comment by DanteAndroid** [comment]
这错误以前也遇到过但是很难重现，你能回想一下**具体的操作步骤以重现这个错误吗**？

**Comment by AndrWang** [comment]
> 在 2016年4月27日，下午3:49，Dante <notifications@github.com> 写道：
> 
> 这错误以前也遇到过但是很难重现，你能回想一下具体的操作步骤以重现这个错误吗？
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/DanteAndroid/Knowledge/issues/7#issuecomment-214997709>
我试了3遍都重现了。。就是随便进进然后退出，回到桌面2s钟就会alert Error

**Comment by liyinyin** [comment]
我也出现这个错误，Realm这玩意感觉不稳定，activity里面获取它的instance的时候，blockcanary也会提示。

**Comment by DanteAndroid** [comment]
这玩意是realm的坑，由于realm这个数据库数据会自动更新，(比如你用realm搜索了某个对象，并设置到adapter里面，如果这个对象改变了，那么adapter里的内容也自动改变)。我已经联系realm帮我解决了，需要一点时间。

**Comment by DanteAndroid** [comment]
不稳定是外在表现，其原因反而是因为realm的强大、快速。当然他还有很多可以完善的地方。毕竟还没发release版本。。

**Comment by liyinyin** [comment]
可以接受pull吗？ 不知道什么原因，上下滑动列表的时候，toolbar那一条出现白屏，设备是小米pad，我抽空调试下。看什么原因。
还有就是友盟自动更新已经下架了，没必要集成了，leakcanary也检测到这货内存泄漏。
打开知乎文章，里面的webview是new 出来的。 直接在布局里面会不会好点。

**Comment by DanteAndroid** [comment]
@liyinyin 欢迎pull，我水平实在有限。友盟更新下架了？上天我还用来着。至于内存泄露。。我用过[bmob](http://www.bmob.cn/)也检测出来内存泄露。所以国内的sdk看来泄露很常见。
你说的toolbar白屏指的是tablayout吗？那样的话，是design库的版本问题。我已经滚回（大雾）23.1.1了。如果你用的是fork的话，可能需要更新下代码。。我修复了一些bug

**Comment by DanteAndroid** [comment]
@liyinyin fork库更新代码的方法：

#先得将原来的仓库指定为upstream
git remote add upstream https://github.com/被fork的仓库.git
#再从原repo获得那边的更改
git fetch upstream
#最后merge到你自己的repo副本里去
git merge upstream/master

**Comment by liyinyin** [comment]
@DanteAndroid tablayout是正常的，只有toolbar高度是白的一片，向下滑动列表的时候。等滑动结束的时候，可能还是白的，然后稍微动下界面，就正常了。我其他项目中也用到了这个效果，没有出现白屏。

友盟自动更新下架没多久。

好的，我先看下。

**Comment by liyinyin** [comment]
@DanteAndroid 你gmail，少个d？danteandroi，在menu"关于"里面。

**Comment by DanteAndroid** [comment]
@liyinyin 感谢提醒，实际上是因为我注册Google账号时，Google好像不允许使用'Android'这个关键词。所以就去掉了d

**Comment by liyinyin** [comment]
@DanteAndroid 哈哈，这样额，收下邮件。加个好友呗~

**Comment by DanteAndroid** [comment]
此bug已经修复。谢谢支持~
