### ISSUE TITLE
关于一段代码何时执行及程序崩溃的问题

### ISSUE THREAD

**Issue by evilchaos** [DanteAndroid/Knowledge#9]
您好，最近一段时间在读您的这个应用源码，有两个问题想请教您 ：
      （1）您的程序我在nexus手机上运行时，经常会出现崩溃的问题，我想是不是您全局变量被回收的原因？
       （2）在pictureFragment.java文件中，if (isFirst && page <= 1) {
            if (lastPosition > images.size() / 3) {
                page = SPUtil.getInt(type + Constants.PAGE);
                fetch(false);
            } 这段代码何时执行，我研究了一阵子都没有弄明白？

**Comment by DanteAndroid** [comment]
1. 崩溃要看log，你可以崩溃后连接AS，也是能显示log的
2. 这段是在第一次进入的时候，且是第一页的时候，如果用户滑到1/3的位置就加载（早点加载，优化体验）
